<?xml version="1.0" encoding="utf-8"?><Database Name="Gestion" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="cliente">
      <Column Name="numclie" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="limitecredito" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>