<?xml version="1.0" encoding="utf-8"?><Database Name="Gestion" Class="LINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FRANCO-NB\ALTAIRSQL;Initial Catalog=Gestion;Integrated Security=True" SettingsObjectName="Gestion.Properties.Settings" SettingsPropertyName="GestionConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="cliente">
      <Column Name="numclie" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="limitecredito" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.productos" Member="productos">
    <Type Name="producto">
      <Column Name="idfab" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="idproducto" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="precio" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="existencias" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.empleados" Member="empleados">
    <Type Name="empleado">
      <Column Name="numemp" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="edad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="oficina" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="contrato" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="jefe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cuota" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ventas" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.oficinas" Member="oficinas">
    <Type Name="oficina">
      <Column Name="oficina" Member="oficina1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ciudad" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="region" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="dir" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="objetivo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ventas" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.pedidos" Member="pedidos">
    <Type Name="pedido">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numpedido" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="fechapedido" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="clie" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fab" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="producto" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cant" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="importe" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>